name: Generate GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"  # تحديث يومي
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    steps:
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: Sara-source01
          THEME: solarized_light
